# Per-application window rules

# 1Password should always open as a floating window.
windowrule=appid:^1password$,isfloating:1,width:1200,height:1000

# Bolt Launcher should always open as a floating window.
windowrule=appid:^BoltLauncher$,isfloating:1,width:1200,height:1000
